pipeline {
    agent any
    environment {
        GIT_TOKEN = credentials('GIT_TOKEN')
    }
    stages {
        stage('Get Code') {
            steps {
                echo 'Download git repository'

                git branch: 'master', url: 'https://${GIT_TOKEN}@github.com/macunagutierrez/todo-list-aws.git'
                echo WORKSPACE
                sh 'dir'
            }
            
        }

        stage('STATIC') {
               
               steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                   sh '''
                       whoami
                       hostname
                       echo ${WORKSPACE}
                       ls
                       flake8 --format=pylint --exit-zero src >flake8.out
                   '''
                   recordIssues tools: [flake8(name: 'Flake8', pattern: 'flake8.out')]
                }
               }
        }
        stage('SECURITY Test') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                sh '''
                    whoami
                    hostname
                    echo ${WORKSPACE}
                    bandit --exit-zero -r . -f custom -o bandit.out --severity-level medium --msg-template "{abspath}:{line}: [{test_id}] {msg}"
                '''
                recordIssues tools: [pyLint(name: 'Bandit', pattern: 'bandit.out')]
                }
            }
        }
        stage('DEPLOY') {
          steps {
              sh '''
              ls
              sam build
              sam deploy --stack-name todo-list-aws --region us-east-1 --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-tsa4u9fez1gg --s3-prefix todo-list-aws --capabilities CAPABILITY_IAM --parameter-overrides Stage=staging --no-fail-on-empty-changeset
              '''
          }
                     
        }
        
       
    }
}
